WITH staging as (

SELECT
    data->>'$.id' AS id,
    data->>'$.city' AS city,
    data->>'$.postalCode' AS postalCode,
    data->>'$.adType' AS adType,
    data->>'$.propertyType' AS propertyType,
    data->>'$.reference' AS reference,
    data->>'$.description' AS description,
    data->>'$.title' AS title,
    data->>'$.publicationDate' AS publicationDate,
    data->>'$.modificationDate' AS modificationDate,
    data->>'$.newProperty' AS newProperty,
    data->>'$.accountType' AS accountType,
    data->>'$.isBienIciExclusive' AS isBienIciExclusive,
    data->>'$.price' AS price,
    data->>'$.surfaceArea' AS surfaceArea,
    data->>'$.roomsQuantity' AS roomsQuantity,
    data->>'$.bedroomsQuantity' AS bedroomsQuantity,
    data->>'$.floor' AS floor,
    data->>'$.floorQuantity' AS floorQuantity,
    data->>'$.showerRoomsQuantity' AS showerRoomsQuantity,
    data->>'$.hasCaretaker' AS hasCaretaker,
    data->>'$.hasTerrace' AS hasTerrace,
    data->>'$.isExclusiveSaleMandate' AS isExclusiveSaleMandate,
    data->>'$.photos' AS photos,
    data->>'$.workToDo' AS workToDo,
    data->>'$.energyValue' AS energyValue,
    data->>'$.energyClassification' AS energyClassification,
    data->>'$.greenhouseGazValue' AS greenhouseGazValue,
    data->>'$.greenhouseGazClassification' AS greenhouseGazClassification,
    data->>'$.isInCondominium' AS isInCondominium,
    data->>'$.condominiumPartsQuantity' AS condominiumPartsQuantity,
    data->>'$.isCondominiumInProcedure' AS isCondominiumInProcedure,
    data->>'$.feesChargedTo' AS feesChargedTo,
    data->>'$.priceWithoutFees' AS priceWithoutFees,
    data->>'$.energyPerformanceDiagnosticDate' AS energyPerformanceDiagnosticDate,
    data->>'$.useJuly2021EnergyPerformanceDiagnostic' AS useJuly2021EnergyPerformanceDiagnostic,
    data->>'$.adCreatedByPro' AS adCreatedByPro,
    data->>'$.departmentCode' AS departmentCode,
    data->>'$.addressKnown' AS addressKnown,
    data->>'$.displayDistrictName' AS displayDistrictName,
    data->>'$.pricePerSquareMeter' AS pricePerSquareMeter,
    data->>'$.postalCodeForSearchFilters' AS postalCodeForSearchFilters,
    data->>'$.descriptionTextLength' AS descriptionTextLength,
    data->>'$.priceHasDecreased' AS priceHasDecreased,
    data->>'$.transactionType' AS transactionType,
    data->>'$.adTypeFR' AS adTypeFR,
    data->>'$.with3dModel' AS with3dModel,
    data->>'$.endOfPromotedAsExclusive' AS endOfPromotedAsExclusive,
    data->>'$.opticalFiberStatus' AS opticalFiberStatus,
    data->>'$.nothingBehindForm' AS nothingBehindForm,
    data->>'$.highlightMailContact' AS highlightMailContact,
    data->>'$.displayInsuranceEstimation' AS displayInsuranceEstimation,
    data->>'$.needVirtualTour' AS needVirtualTour,
    data->>'$.phoneDisplays' AS phoneDisplays,
    data->>'$.blurInfo' AS blurInfo,
    data->>'$.chargingStations' AS chargingStations,
    data->>'$.district' AS district,
    data->>'$.status' AS status,
    data->>'$.userRelativeData' AS userRelativeData,
    data->>'$.hasCellar' AS hasCellar,
    data->>'$.hasDoorCode' AS hasDoorCode,
    data->>'$.exposition' AS exposition,
    data->>'$.heating' AS heating,
    data->>'$.hasSeparateToilet' AS hasSeparateToilet,
    data->>'$.hasPool' AS hasPool,
    data->>'$.minEnergyConsumption' AS minEnergyConsumption,
    data->>'$.maxEnergyConsumption' AS maxEnergyConsumption,
    data->>'$.energySimulationReferenceDate' AS energySimulationReferenceDate,
    data->>'$.epdFinalEnergyConsumption' AS epdFinalEnergyConsumption,
    data->>'$.hasGeorisquesMention' AS hasGeorisquesMention,
    data->>'$.virtualTours' AS virtualTours,
    data->>'$.hasAlarm' AS hasAlarm,
    data->>'$.hasIntercom' AS hasIntercom,
    data->>'$.annualCondominiumFees' AS annualCondominiumFees,
    data->>'$.hasFirePlace' AS hasFirePlace,
    data->>'$.thresholdDate' AS thresholdDate,
    data->>'$.yearOfConstruction' AS yearOfConstruction,
    data->>'$.photoWatermarkAlias' AS photoWatermarkAlias,
    data->>'$.accountDisplayName' AS accountDisplayName,
    data->>'$.bathroomsQuantity' AS bathroomsQuantity,
    data->>'$.toiletQuantity' AS toiletQuantity,
    data->>'$.hasElevator' AS hasElevator,
    data->>'$.parkingPlacesQuantity' AS parkingPlacesQuantity,
    data->>'$.hasAirConditioning' AS hasAirConditioning,
    data->>'$.isDisabledPeopleFriendly' AS isDisabledPeopleFriendly,
    data->>'$.averageAnnualEnergyConsumption' AS averageAnnualEnergyConsumption,
    data->>'$.customerId' AS customerId,
    data->>'$.agencyFeeUrl' AS agencyFeeUrl,
    data->>'$.agencyFeePercentage' AS agencyFeePercentage,
    data->>'$.terracesQuantity' AS terracesQuantity,
    data->>'$.balconyQuantity' AS balconyQuantity,
    data->>'$.cellarsOrUndergroundsQuantity' AS cellarsOrUndergroundsQuantity,
    data->>'$.isCalm' AS isCalm,
    data->>'$.isRecent' AS isRecent,
    data->>'$.condominiumDetailedProcedure' AS condominiumDetailedProcedure,
    data->>'$.isRefurbished' AS isRefurbished,
    data->>'$.hasTVCable' AS hasTVCable,
    data->>'$.isDuplex' AS isDuplex,
    data->>'$.isStudio' AS isStudio,
    data->>'$.needHomeStaging' AS needHomeStaging
FROM {{ source('raw_data', 'bienici') }}
),

filters_duplicate AS (
    SELECT
        *,
        ROW_NUMBER() OVER (PARTITION BY city, postalCode, adType, propertyType
                           ORDER BY modificationDate DESC) AS rn
    FROM staging
)

SELECT *
FROM filters_duplicate
WHERE rn = 1
